### ISSUE TITLE
Latency and Memory Footprint measurements

### ISSUE THREAD

**Issue by minhducquach** [bytedance/R2Former#12]
Thank you for your work! I would like to ask about how did you measure the latency per query and the memory footprint of the method?

**Comment by szhu-bytedance** [comment]
You may add time measurement using time.time(). You can use the getsizeof ("from sys import getsizeof") function to get the size of the numpy array for global/local features.

**Comment by szhu-bytedance** [comment]
I will close the issue if there is no further question.
