### ISSUE TITLE
Could you please give me the code of how to draw the two thermal degrees on the right of Figure 3

### ISSUE THREAD

**Issue by Lavau** [bytedance/R2Former#14]
Hello! My question is, can you give me the code of how to draw the two thermal degrees on the right of Figure 3? I looked through the code you published, but did not find the relevant part.  Could you share it with me if you can? Thank you very much. If it's difficult, that's fine. Thank you for your wonderful work ! ! !

**Comment by szhu-bytedance** [comment]
Thanks for your interest. It is a simple plot using matplotlib, but we cannot provide the exact code for this part.

**Comment by Lavau** [comment]
Thanks for your reply! Good Luck.
