### ISSUE TITLE
dealing with one-channel input

### ISSUE THREAD

**Issue by noahzn** [bytedance/R2Former#15]
Hi, thanks for sharing the code!

If I want to input one-channel images and still use the pretrained DeiT, how should I modify the code? I tried changing `in_chans=1` in `class AnySizePatchEmbed`, but encountered the channel problem. `RuntimeError: Given groups=1, weight of size [384, 3, 16, 16], expected input[7, 1, 512, 512] to have 3 channels, but got 1 channels instead
`

**Comment by Anuradha-Uggi** [comment]
Hi. Try repeating the single channel across 3 channels and feed it to the model.
