### ISSUE TITLE
About variable image size of Tokyo 24/7 dataset

### ISSUE THREAD

**Issue by xjh19971** [bytedance/R2Former#4]
Hi, another question about variable image size from Tokyo 24/7 dataset. As I understand, visual transformer requires a fixed image size. How does R2former preprocess for the variable image size? Is it just resizing or some other methods like padding and resizing to maintain the aspect ratio? Thank you!

**Comment by Jeff-Zilence** [comment]
I think we resize them to the same size in the experiments, but our model can handle arbitrary image sizes directly. If you check the code of our model, we have a positional embedding interpolation so that it can adjust based on the size.

**Comment by Jeff-Zilence** [comment]
I will close this issue if there is no further question.

**Comment by xjh19971** [comment]
No problem. Thanks!
