### ISSUE TITLE
Question about ResNet pretrained model

### ISSUE THREAD

**Issue by jinxxo-j** [bytedance/R2Former#7]
Thank you for your research!
I have a question, when I look at the code, there are ResNet-50 pretrained weights for places dataset and gldv2 dataset, but which ResNet-50 pretrained backbone did you use for ResNet-50 + GeM (Ours w/o reranking) performance in the main paper table 6?

**Comment by jinxxo-j** [comment]
+ for training global retrieval model (ResNet-50 + GeM pool), the dimension of feature is 1024?

**Comment by Jeff-Zilence** [comment]
Can you directly run the code? The implementation of ResNet50+GeM is also included in the code. And the first stage training is based on the Geo-localization benchmark repo with standard setting. Use backbone="resnet50" in the command.
