### ISSUE TITLE
Question about setting of pitts30k training

### ISSUE THREAD

**Issue by Graysonggg** [bytedance/R2Former#9]
Great work!
I would like to inquire about the specific parameter settings for training on the pitts30k dataset.
 Can you provide files similar to train_ Deit.sh and train_reranker.sh when training models only on pitts30k?
Thank you!

**Comment by Graysonggg** [comment]
I notice that you trained the model on pitts30k mentioned in supplementary Material's Table 1. The model size is large and pitts30k is small. Can you just give more training details? Thank you.

**Comment by Jeff-Zilence** [comment]
Pitts30K is small and there is no need to use my global mining strategy. You can change the --mining to full and run the same command in train_reranker.sh. The deit-s model is actually very small and you should be able to get similar results with standard setting.

**Comment by szhu-bytedance** [comment]
I will close the issue if there is no further question.
